# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trailguard.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'trailguard.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10trailguard.proto\x12\ntrailguard\"\x7f\n\x08NodeInfo\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x13\n\x0b\x62\x61ttery_pct\x18\x04 \x01(\x02\x12\x10\n\x08solar_mw\x18\x05 \x01(\x02\x12\x16\n\x0elast_seen_unix\x18\x06 \x01(\r\"W\n\x07\x43heckIn\x12\x10\n\x08hiker_id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x16\n\x0etimestamp_unix\x18\x03 \x01(\r\x12\x11\n\tsignature\x18\x04 \x01(\x0c\"\x8a\x01\n\x03SOS\x12\x10\n\x08hiker_id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x16\n\x0etimestamp_unix\x18\x03 \x01(\r\x12\x11\n\thiker_lat\x18\x04 \x01(\x01\x12\x11\n\thiker_lon\x18\x05 \x01(\x01\x12\x0f\n\x07message\x18\x06 \x01(\t\x12\x11\n\tsignature\x18\x07 \x01(\x0c\"\x97\x01\n\x0cTrailMessage\x12\x10\n\x08hiker_id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x16\n\x0etimestamp_unix\x18\x03 \x01(\r\x12&\n\x06preset\x18\x04 \x01(\x0e\x32\x16.trailguard.PresetCode\x12\x11\n\tfree_text\x18\x05 \x01(\t\x12\x11\n\tsignature\x18\x06 \x01(\x0c\"Q\n\x03\x41\x63k\x12\x1b\n\x13original_message_id\x18\x01 \x01(\t\x12\x1a\n\x12\x61\x63k_timestamp_unix\x18\x02 \x01(\r\x12\x11\n\tsignature\x18\x03 \x01(\x0c*\xb2\x01\n\nPresetCode\x12\x16\n\x12PRESET_UNSPECIFIED\x10\x00\x12\x12\n\x0e\x41LL_OK_DELAYED\x10\x01\x12\x17\n\x13MINOR_INJURY_MOBILE\x10\x02\x12\x19\n\x15LOW_ON_WATER_SUPPLIES\x10\x03\x12\x18\n\x14WEATHER_TURNING_BACK\x10\x04\x12\x19\n\x15NEED_NONURGENT_ASSIST\x10\x05\x12\x0f\n\x0b\x43USTOM_TEXT\x10\x0f\x42*\n\x17\x63om.trailguard.protocolB\x0fTrailGuardProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trailguard_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.trailguard.protocolB\017TrailGuardProto'
  _globals['_PRESETCODE']._serialized_start=629
  _globals['_PRESETCODE']._serialized_end=807
  _globals['_NODEINFO']._serialized_start=32
  _globals['_NODEINFO']._serialized_end=159
  _globals['_CHECKIN']._serialized_start=161
  _globals['_CHECKIN']._serialized_end=248
  _globals['_SOS']._serialized_start=251
  _globals['_SOS']._serialized_end=389
  _globals['_TRAILMESSAGE']._serialized_start=392
  _globals['_TRAILMESSAGE']._serialized_end=543
  _globals['_ACK']._serialized_start=545
  _globals['_ACK']._serialized_end=626
# @@protoc_insertion_point(module_scope)
